(define (problem designenvp1)
(:domain designenvp)
(:init
(= (total-cost) 0)
	(connect loc1 loc2)
	(connect loc2 loc1)
	(connect loc2 loc3)
	(connect loc3 loc2)
	(connect loc3 loc4)
	(connect loc4 loc3)
	(connect loc4 loc5)
	(connect loc5 loc4)
	(connect loc5 loc6)
	(connect loc6 loc5)
	(armat loc1)
	(armempty)
	(boxat box1 loc1)
	(boxat box2 loc1)
	(boxat box3 loc1)
	(on box3 box2)
	(on box2 box1)
	(ontable box1)
	(cleartable loc2)
	(cleartable loc3)
	(cleartable loc4)
	(cleartable loc5)
	(cleartable loc6)
)
(:goal 
(and (boxAt box2 loc3 ) (boxAt box3 loc2 ) (boxat box1 loc2) (goalAchieved )))
(:metric minimize (total-cost))
)
